DATASET: 'CustomDataset'
DATA_PATH: 'path/to/workspace'

POINT_CLOUD_RANGE: [-50, -103.6, -0.1, 103.6, 50, 4.1]
# POINT_CLOUD_RANGE: [-80, -103.6, -0.1, 73.60, 50, 4.1]

MAP_CLASS_TO_KITTI: {
    'car': 'Car',
    'pedestrians': 'Pedestrian',
    'non_motor_vehicleslist': 'Cyclist',
    'truck': 'Truck',
    'bus' : 'Van',
    'other_obstacles': 'DontCare'
}

DATA_SPLIT: {
    'train': train,
    'test': test
}

INFO_PATH: {
    'train': [custom_infos_train.pkl],
    'test': [custom_infos_test.pkl],
}

POINT_FEATURE_ENCODING: {
    encoding_type: absolute_coordinates_encoding,
    used_feature_list: ['x', 'y', 'z', 'intensity'],
    src_feature_list: ['x', 'y', 'z', 'intensity'],
}

DATA_AUGMENTOR:
    DISABLE_AUG_LIST: ['placeholder']
    AUG_CONFIG_LIST:
        - NAME: gt_sampling
          USE_ROAD_PLANE: False
          DB_INFO_PATH:
              - custom_dbinfos_train.pkl
          PREPARE: {
             filter_by_min_points: ["car:5", "truck:5", "bus:5", "non_motor_vehicleslist:5", "pedestrians:5", "other_obstacles:5"],
          }

          SAMPLE_GROUPS: ["car:15", "truck:15", "bus:15", "non_motor_vehicleslist:15", "pedestrians:15", "other_obstacles:5"]
          NUM_POINT_FEATURES: 4
          DATABASE_WITH_FAKELIDAR: False
          REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
          LIMIT_WHOLE_SCENE: True

        - NAME: random_world_flip
          ALONG_AXIS_LIST: ['x', 'y']

        - NAME: random_world_rotation
          WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]

        - NAME: random_world_scaling
          WORLD_SCALE_RANGE: [0.95, 1.05]

DATA_PROCESSOR:
    - NAME: mask_points_and_boxes_outside_range
      REMOVE_OUTSIDE_BOXES: True

    - NAME: shuffle_points
      SHUFFLE_ENABLED: {
        'train': True,
        'test': False
      }

    - NAME: transform_points_to_voxels
      VOXEL_SIZE: [0.32, 0.32, 4.2]
      MAX_POINTS_PER_VOXEL: 32
      MAX_NUMBER_OF_VOXELS: {
        'train': 60000,
        'test': 60000
      }